app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('about/',views.about, name='about'),
    path('contact/',views.contact, name='contact'),
    path('view_product/<slug:slug>/',views.view_product, name='view_product'),
    path('category_filter/<slug:slug>/',views.category_filter, name='category_filter'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart, name='add_to_cart'),
    path('view_cart/',views.view_cart, name='view_cart'),
    path('manage_cart/<int:cp_id>/',views.manage_cart, name='manage_cart'),
    path('check_out/',views.check_out, name='checkout'),
    path('signup/',views.signup, name='signup'),
    path('login/',views.customer_login, name='login'),
    path('logout/',views.logout, name='logout'),
]

project_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name
    

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title
    
class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE) 
    image = models.ImageField(upload_to='Productimages')
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=50, null=True, blank=True)
    return_policy = models.CharField(max_length=50, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

class Cart(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.id) + " CartProduct: " + str(self.id)

ORDER_STATUS = (
    ("Order Received","Order Received"),
    ("Order Processing","Order Processing"),
    ("On the way","On the way"),
    ("Order Completed","Order Completed"),
    ("Order Canceled","Order Canceled"),
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(max_length=254) 
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)
    

templates/app/about.html
{% extends 'app/base.html' %}
{% load static %}

{% block category %}
  <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
  {% for i in category %}
    <a class="dropdown-item" href="{% url 'category_filter' i.slug %}">{{i.title|capfirst}}</a>
  {% endfor %}
{% endblock category %}

{% block content %}
    <div class="container">
        <br>
        <h3>About us</h3>
        <h6>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident maxime eaque culpa alias, itaque modi porro similique non aspernatur, magnam minus vitae earum, rem dignissimos. Quae vitae omnis, pariatur blanditiis eaque illo odit! Veritatis nemo quas sit blanditiis illo neque vel id cupiditate rem culpa quia illum provident tempora, qui eveniet soluta nam tempore unde temporibus iusto beatae! Magni mollitia, rerum soluta minima, corporis velit eaque nemo exercitationem nam, dolorum unde. Distinctio ipsum, repellat dolore facilis magni et veritatis accusamus temporibus. Nisi consequuntur aut quis iure ipsum perferendis hic, velit soluta quidem nihil sint officia nostrum ducimus culpa dolorem vero?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident maxime eaque culpa alias, itaque modi porro similique non aspernatur, magnam minus vitae earum, rem dignissimos. Quae vitae omnis, pariatur blanditiis eaque illo odit! Veritatis nemo quas sit blanditiis illo neque vel id cupiditate rem culpa quia illum provident tempora, qui eveniet soluta nam tempore unde temporibus iusto beatae! Magni mollitia, rerum soluta minima, corporis velit eaque nemo exercitationem nam, dolorum unde. Distinctio ipsum, repellat dolore facilis magni et veritatis accusamus temporibus. Nisi consequuntur aut quis iure ipsum perferendis hic, velit soluta quidem nihil sint officia nostrum ducimus culpa dolorem vero?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident maxime eaque culpa alias, itaque modi porro similique non aspernatur, magnam minus vitae earum, rem dignissimos. Quae vitae omnis, pariatur blanditiis eaque illo odit! Veritatis nemo quas sit blanditiis illo neque vel id cupiditate rem culpa quia illum provident tempora, qui eveniet soluta nam tempore unde temporibus iusto beatae! Magni mollitia, rerum soluta minima, corporis velit eaque nemo exercitationem nam, dolorum unde. Distinctio ipsum, repellat dolore facilis magni et veritatis accusamus temporibus. Nisi consequuntur aut quis iure ipsum perferendis hic, velit soluta quidem nihil sint officia nostrum ducimus culpa dolorem vero?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident maxime eaque culpa alias, itaque modi porro similique non aspernatur, magnam minus vitae earum, rem dignissimos. Quae vitae omnis, pariatur blanditiis eaque illo odit! Veritatis nemo quas sit blanditiis illo neque vel id cupiditate rem culpa quia illum provident tempora, qui eveniet soluta nam tempore unde temporibus iusto beatae! Magni mollitia, rerum soluta minima, corporis velit eaque nemo exercitationem nam, dolorum unde. Distinctio ipsum, repellat dolore facilis magni et veritatis accusamus temporibus. Nisi consequuntur aut quis iure ipsum perferendis hic, velit soluta quidem nihil sint officia nostrum ducimus culpa dolorem vero?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident maxime eaque culpa alias, itaque modi porro similique non aspernatur, magnam minus vitae earum, rem dignissimos. Quae vitae omnis, pariatur blanditiis eaque illo odit! Veritatis nemo quas sit blanditiis illo neque vel id cupiditate rem culpa quia illum provident tempora, qui eveniet soluta nam tempore unde temporibus iusto beatae! Magni mollitia, rerum soluta minima, corporis velit eaque nemo exercitationem nam, dolorum unde. Distinctio ipsum, repellat dolore facilis magni et veritatis accusamus temporibus. Nisi consequuntur aut quis iure ipsum perferendis hic, velit soluta quidem nihil sint officia nostrum ducimus culpa dolorem vero?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident maxime eaque culpa alias, itaque modi porro similique non aspernatur, magnam minus vitae earum, rem dignissimos. Quae vitae omnis, pariatur blanditiis eaque illo odit! Veritatis nemo quas sit blanditiis illo neque vel id cupiditate rem culpa quia illum provident tempora, qui eveniet soluta nam tempore unde temporibus iusto beatae! Magni mollitia, rerum soluta minima, corporis velit eaque nemo exercitationem nam, dolorum unde. Distinctio ipsum, repellat dolore facilis magni et veritatis accusamus temporibus. Nisi consequuntur aut quis iure ipsum perferendis hic, velit soluta quidem nihil sint officia nostrum ducimus culpa dolorem vero?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident maxime eaque culpa alias, itaque modi porro similique non aspernatur, magnam minus vitae earum, rem dignissimos. Quae vitae omnis, pariatur blanditiis eaque illo odit! Veritatis nemo quas sit blanditiis illo neque vel id cupiditate rem culpa quia illum provident tempora, qui eveniet soluta nam tempore unde temporibus iusto beatae! Magni mollitia, rerum soluta minima, corporis velit eaque nemo exercitationem nam, dolorum unde. Distinctio ipsum, repellat dolore facilis magni et veritatis accusamus temporibus. Nisi consequuntur aut quis iure ipsum perferendis hic, velit soluta quidem nihil sint officia nostrum ducimus culpa dolorem vero?
        </h6>
    </div>
        
{% endblock content %}

templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ecommerce-STORE</title>
  <link rel="stylesheet" href="{% static 'app/css/bootstrap1.css' %}">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark" style="height: 1.85cm; background-color: rgb(77, 121, 118);">
    <div class="container-fluid mx-2">
      <a class="navbar-brand" href="{% url 'home' %}" style="padding-left: 20px;"> <b> Ecommerce-STORE </b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}"> <b style="color: white;">About</b> </a>
          </li>
          <li class="nav-item active ">
            <a class="nav-link" href="{% url 'contact' %}"> <b style="color: white;">Contact</b> </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false" style="color: white;"> <b>Products</b> </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% block category %}
              <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
              {% endblock category %}
            </div>
          </li>
        </ul>
        {% if not request.user.is_authenticated %}
          <div style="padding-left: 20px;">
            <a href="{% url 'signup' %}" class="btn btn-warning"><b>Signup</b></a>
          </div>
          <div style="padding-left: 10px;">
            <a href="{% url 'login' %}" class="btn btn-warning"><b>Login</b></a>
          </div>
        {% endif %}

      </div>
      {% if request.user.is_authenticated %}
        <form class="d-flex" action="{% url 'logout' %}" method="POST">
          {% csrf_token %}
          <button type="submit"  class="btn btn-warning"><b>Logout</b></button>
        </form>  
      {% endif %}
    </div>
    <a href="{% url 'view_cart' %}"><img style="height: 40px; padding-right: 35px;"
        src="{% static 'app/images/cart1.png' %}"></img></a>
  </nav>

  <div class="container">
    <div class="row">

      {% block content %}


      {% endblock content %}

    </div>
  </div>


  <script src="{% static 'app/js/jquery.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.js' %}"></script>
  <script src="{% static 'app/js/popper.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
    integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
    integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
    crossorigin="anonymous"></script>
</body>

</html>

templates/app/cart.html
{% extends 'app/base.html' %}
{% load static %}

{% block category %}
  <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
  {% for i in category %}
    <a class="dropdown-item" href="{% url 'category_filter' i.slug %}">{{i.title|capfirst}}</a>
  {% endfor %}
{% endblock category %}


{% block content %}
  <h1 class="text-center my-2">My Cart</h1>
            <table class="table">
                <thead class="thead-dark" >
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in cart.cartproduct_set.all %}
                      <tr>
                        <th>{{forloop.counter}}</th>
                        <th>{{i.product.title}}</th>
                        <th>{{i.rate}}</th>
                        <th>{{i.quantity}}</th>
                        <th>{{i.subtotal}}</th>
                        <th>
                          <a href="{% url 'manage_cart' i.id %}?action=inc" class="btn btn-primary"> + </a>
                          <a href="{% url 'manage_cart' i.id %}?action=dcr" class="btn btn-warning"> - </a>
                          <a href="{% url 'manage_cart' i.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </th>
                      </tr>
                    {% endfor %}
                    <tr>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th>Total</th>
                      <th>{{cart.total}}</th>
                      <th></th>
                    </tr>

                    {% if cart.cartproduct_set.all %}
                      <tr>
                        <th><a href="{% url 'checkout' %}"class="btn btn-info">Checkout</a></th>
                      </tr>                      
                    {% endif %}
                </tbody>
            </table>
  
{% endblock content %}

templates/app/checkout.html
{% extends 'app/base.html' %}
{% load static %}

{% block category %}
  <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
  {% for i in category %}
    <a class="dropdown-item" href="{% url 'category_filter' i.slug %}">{{i.title|capfirst}}</a>
  {% endfor %}
{% endblock category %}


{% block content %}

  {% if cart %}
    
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <h1 class="text-center my-2">Checkout!</h1>
            <table class="table">
                <thead class="thead-dark" >
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in cart.cartproduct_set.all %}
                      <tr>
                        <th>{{forloop.counter}}</th>
                        <th>{{i.product.title}}</th>
                        <th>{{i.rate}}</th>
                        <th>{{i.quantity}}</th>
                        <th>{{i.subtotal}}</th>
                      </tr>
                    {% endfor %}
                    <tr>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th>Total</th>
                      <th>{{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
      </div>
      <div class="col-sm mx-3">
        <h1 class="mx-2 my-2" >Checkout form</h1>
        <form class="row g-3" action="{% url 'checkout' %}" method="post">
            {% csrf_token %}
            {% for fm in form %}
                <div class=" mx-3 col-md-6">
                    <label class="form-label" for= {{field.auto_id}} >{{ fm.label_tag }}</label> 
                    {{fm}} 
                    <br> 
                    {% if fm.errors %}
                        <div style="color: rgb(255, 2, 2);" >{{fm.errors|striptags}}</div>  
                    {% endif %}
                </div>
            {% endfor %}
            <div class="mx-3 col-12">
                <button type="submit" class="btn btn-success">Checkout</button>
            </div>
        </form>

      </div>
    </div>
  </div>
  {% else %}
    <h4 class="mx-3 my-3" >no Product is still added to cart!</h4>
  {% endif %}

  
{% endblock content %}

templates/app/contact.html
{% extends 'app/base.html' %}
{% load static %}

{% block category %}
  <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
  {% for i in category %}
    <a class="dropdown-item" href="{% url 'category_filter' i.slug %}">{{i.title|capfirst}}</a>
  {% endfor %}
{% endblock category %}

{% block content %}
<h1 class="mx-3 px-3 my-3 py-3 text-center" >Contact us!</h1>
<form class="mx-3 px-3 my-3 py-3" action="{% url 'contact' %}"method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleFormControlInput">Name : </label>
        <br>
        <input type="name" name="name" type="text" required class="form-control" id="exampleFormControlInput" placeholder="name..">  
        <br>
        <label for="exampleFormControlInput1">Email address : </label>
        <br>
        <input type="email" name="mail" type="email" required class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
        <br>
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Comments : </label>
      <textarea class="form-control" name="msg" type="text" required id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock content %}

templates/app/home.html
{% extends 'app/base.html' %}
{% load static %}

{% block category %}
  <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
  {% for i in category %}
    <a class="dropdown-item" href="{% url 'category_filter' i.slug %}">{{i.title|capfirst}}</a>
  {% endfor %}
{% endblock category %}


{% block content %}
  <h1 class="text-center my-2" >Welcome to Our Ecommerce-Store</h1>
  <div class="container row mx-2 my-2" >
    <h2 class="mx-2" >
      {% if category_name %}
        {{category_name|capfirst}}
      {% else %}
        All Products
      {% endif %}
    </h2>
    {% if data %}
      {% for cat in category %}
        <h4 class="mx-2">{{cat.title|capfirst}}</h4>
        {% for i in cat.product_set.all %}
          <div class="shadow card mx-3 my-3" style="width: 18rem;">
            <img src="{{ i.image.url }}" class="card-img-top" style="width: 7cm; height: 7cm;" alt="">
            <div class="card-body">
              <h5 class="card-title">{{i.title}}</h5>
              <p class="card-text">{{i.description}}</p>
              <p class="card-text">Warranty : {{i.warranty}}</p>
              <p class="card-text">Return Policy : {{i.return_policy}}</p>
              <p class="card-text">Rs. <strike>{{i.marked_price}}</strike> Rs. {{i.selling_price}}</p>

              <a href="{% url 'add_to_cart' i.id %}" class="btn btn-warning">Add to Cart</a>
              <a href="{% url 'view_product' i.slug %}" class="btn btn-warning">View</a>
            </div>
          </div>
        {% endfor %}
      {% endfor %}
    {% else %}
      <h3 class="mx-3">no Products</h3>
    {% endif %}
    
  </div>
  
{% endblock content %}

templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}

{% block category %}
  <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
  {% for i in category %}
    <a class="dropdown-item" href="{% url 'category_filter' i.slug %}">{{i.title|capfirst}}</a>
  {% endfor %}
{% endblock category %}

{% block content %}

    <div class="col-sm-6 container">
        <h1 class="my-5 text-center">LOGIN!</h1>
        <form class="row g-3" action="{% url 'login' %}" method="post">
            {% csrf_token %} 
            {% for fm in fm %}
                <div class="col-md-12 mb-3">
                    <label class="form-label" for={{ field.auto_id }}>{{ fm.label_tag }}</label> 
                    {{fm}} {{fm.errors|striptags}} 
                </div>
            {% endfor %}
            {% if messages %}
                {% for message in messages %}
                    {%if "login" in message.tags %}
                    <div class="container" style="color: rgb(255, 2, 2); margin-top: -2px;" >
                        {{message}}
                    </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <div class="col-12">
                <button type="submit" class="btn btn-success">Login</button>
                <a href="{% url 'signup' %}" style="color: rgb(16, 146, 92); margin-left: 15px;" >Register?</a>
            </div>
        </form>
    </div>
        
{% endblock content %}

templates/app/signup.html
{% extends 'app/base.html' %}
{% load static %}

{% block category %}
  <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
  {% for i in category %}
    <a class="dropdown-item" href="{% url 'category_filter' i.slug %}">{{i.title|capfirst}}</a>
  {% endfor %}
{% endblock category %}

{% block content %}
    
    <div class="col-sm-10 container">
        <h1 class="my-5 text-center">Create an Account!</h1>

        <form class="row g-3" action="{% url 'signup' %}" method="post">
            {% csrf_token %}
            {% for fm in fm %}
                <div class="col-md-6">
                    <label class="form-label" for={{ field.auto_id }}>{{ fm.label_tag }}</label> 
                    {{fm}} 
                    <br> 
                    {% if fm.errors %}
                        <div style="color: rgb(255, 2, 2);" >{{fm.errors|striptags}}</div>  
                    {% endif %}
                </div>
            {% endfor %}
            <div class="col-12">
                <button type="submit" class="btn btn-success">Signup</button>
                <a href="{% url 'login' %}" style="color: rgb(16, 146, 92); margin-left: 15px;" >Have an account?</a>
              </div>
        </form>

        
        <br>
        <br>
        <br>
        <br>
        
    </div>
        
{% endblock content %}

templates/app/view_one_category.html
{% extends 'app/base.html' %}
{% load static %}

{% block category %}
  <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
  {% for i in category %}
    <a class="dropdown-item" href="{% url 'category_filter' i.slug %}">{{i.title|capfirst}}</a>
  {% endfor %}
{% endblock category %}

{% block content %}

  <div class="container row mx-2 my-2" >
    <h2 class="mx-2">{{category_name|capfirst}}</h2>
    {% if data %}
      {% for i in data %}
        <div class="shadow card mx-3 my-3" style="width: 18rem;">
          <img src="{{ i.image.url }}" class="card-img-top" style="width: 7cm; height: 7cm;" alt="">
          <div class="card-body">
            <h5 class="card-title">{{i.title}}</h5>
            <p class="card-text">{{i.description}}</p>
            <p class="card-text">Warranty : {{i.warranty}}</p>
            <p class="card-text">Return Policy : {{i.return_policy}}</p>
            <p class="card-text">Rs. <strike>{{i.marked_price}}</strike> Rs. {{i.selling_price}}</p>

            <a href="{% url 'add_to_cart' i.id %}" class="btn btn-warning">Add to Cart</a>
            <a href="{% url 'view_product' i.slug %}" class="btn btn-warning">View</a>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h1>no Products</h1>
    {% endif %}
    
  </div>
  
{% endblock content %}

templates/app/view_one_product.html
{% extends 'app/base.html' %}
{% load static %}

{% block category %}
  <a class="dropdown-item" href="{% url 'home' %}">All Products</a>
  {% for i in category %}
    <a class="dropdown-item" href="{% url 'category_filter' i.slug %}">{{i.title|capfirst}}</a>
  {% endfor %}
{% endblock category %}

{% block content %}
  {% if data %}
    <div class="container">
      <br>
      <h3>Product: {{data.title|capfirst}}</h3><hr>
      <div class="row">
        <div class="col-md-6 text-center">
          <img src="{{data.image.url}}" alt="" style="height: 13cm;" >
        </div>
        <div class="col-md-6">
          <h4>{{data.title|capfirst}}</h4>
          <h5>Category: {{data.category}}</h5>
          <h5>Price: <strike>{{data.marked_price}}</strike> Rs. {{data.selling_price}} </h5>
          <a href="{% url 'add_to_cart' data.id %}" class="btn btn-warning">Add to Cart</a>
          <br>
          <br>
          <p class="card-text">Warranty : {{data.warranty}}</p>
          <p class="card-text">Return Policy : {{data.return_policy}}</p>
          <p class="card-text">{{data.description}}</p>

        </div>
      </div>
    </div>
  {% endif %}
  
{% endblock content %}